kind: Template
apiVersion: v1
metadata:
  annotations:
    tags: nfsautoprovisioner
  name: nfsautoprovisioner
objects:
- kind: Namespace
  apiVersion: v1
  metadata:
    name: "${NAMESPACE_NFS}"
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: nfs-client-provisioner
    namespace: "${NAMESPACE_NFS}"
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: nfs-client-provisioner-runner
  rules:
    - apiGroups: [""]
      resources: ["persistentvolumes"]
      verbs: ["get", "list", "watch", "create", "delete"]
    - apiGroups: [""]
      resources: ["persistentvolumeclaims"]
      verbs: ["get", "list", "watch", "update"]
    - apiGroups: ["storage.k8s.io"]
      resources: ["storageclasses"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["create", "update", "patch"]
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: run-nfs-client-provisioner
  subjects:
    - kind: ServiceAccount
      name: nfs-client-provisioner
      namespace: "${NAMESPACE_NFS}"
  roleRef:
    kind: ClusterRole
    name: nfs-client-provisioner-runner
    apiGroup: rbac.authorization.k8s.io
- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: leader-locking-nfs-client-provisioner
    namespace: "${NAMESPACE_NFS}"
  rules:
    - apiGroups: [""]
      resources: ["endpoints"]
      verbs: ["get", "list", "watch", "create", "update", "patch"]
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: leader-locking-nfs-client-provisioner
    namespace: "${NAMESPACE_NFS}"
  subjects:
    - kind: ServiceAccount
      name: nfs-client-provisioner
  roleRef:
    kind: Role
    name: leader-locking-nfs-client-provisioner
    apiGroup: rbac.authorization.k8s.io
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: nfs-client-provisioner
    namespace: "${NAMESPACE_NFS}"
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: nfs-client-provisioner
      spec:
        serviceAccountName: nfs-client-provisioner
        containers:
          - name: nfs-client-provisioner
            image: quay.io/external_storage/nfs-client-provisioner:latest
            volumeMounts:
              - name: nfs-client-root
                mountPath: /persistentvolumes
            env:
              - name: PROVISIONER_NAME
                value: "nfs-provisioner"
              - name: NFS_SERVER
                value: "${NFS_SERVER}"
              - name: NFS_PATH
                value: "${NFS_PATH}"
        volumes:
          - name: nfs-client-root
            nfs:
              server: "${NFS_SERVER}"
              path: "${NFS_PATH}"
- kind: StorageClass
  apiVersion: storage.k8s.io/v1

  metadata:
    name: managed-nfs-storage
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
  provisioner: "nfs-provisioner"
  parameters:
    archiveOnDelete: "false"
parameters:
  - name: NFS_SERVER
    displayName: NFS Server IP
    description: IP of the NFS server
    required: true
  - name: NFS_PATH
    displayName: NFS Path
    description: Path on the NFS server
    required: true
  - name: NAMESPACE_NFS
    displayName: Namespace for NFS
    description: Namespace for NFS
    required: true
    value: "nfs-autoprovisioner"
